
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Products      <small><?= cclang('detail', ['Products']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/products'); ?>">Products</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Products</h3>
                     <h5 class="widget-user-desc">Detail Products</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_products" id="form_products" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Id </label>

                        <div class="col-sm-8">
                           <?= _ent($products->product_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Name </label>

                        <div class="col-sm-8">
                           <?= _ent($products->product_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Count </label>

                        <div class="col-sm-8">
                           <?= _ent($products->product_count); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Price </label>

                        <div class="col-sm-8">
                           <?= _ent($products->product_price); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Product Image </label>
                        <div class="col-sm-8">
                             <?php if (is_image($products->product_image)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/products/' . $products->product_image; ?>">
                                <img src="<?= BASE_URL . 'uploads/products/' . $products->product_image; ?>" class="image-responsive" alt="image products" title="product_image products" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/products/' . $products->product_image; ?>">
                                 <img src="<?= get_icon_file($products->product_image); ?>" class="image-responsive" alt="image products" title="product_image <?= $products->product_image; ?>" width="40px"> 
                               <?= $products->product_image ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($products->status); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Cat Id </label>

                        <div class="col-sm-8">
                           <?= _ent($products->category_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Description </label>

                        <div class="col-sm-8">
                           <?= _ent($products->description); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Barcode </label>

                        <div class="col-sm-8">
                           <?= _ent($products->barcode); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Product Price Offer </label>

                        <div class="col-sm-8">
                           <?= _ent($products->product_price_offer); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('products_update', function() use ($products){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit products (Ctrl+e)" href="<?= site_url('administrator/products/edit/'.$products->product_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Products']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/products/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Products']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
